### ISSUE TITLE
Simulation failed to run on CPU

### ISSUE THREAD

**Issue by xx005fs** [ProjectPhysX/FluidX3D#101]
I'm currently on Windows 10 using Visual Studio 2019 trying to run some of the default setups with my Ryzen 9 7950X3D CPU, and it seems to work fine with the benchmark runs and simulation runs without loading in an STL file, but once I tried running one that needs to load in an STL file, it throws this error in Visual Studio. Any clues on how to fix it?

`Exception thrown at 0x000002B4E5944539 in FluidX3D.exe: 0xC0000005: Access violation reading location 0x000002B4F875A0C0.`

**Comment by ProjectPhysX** [comment]
Hi @xx005fs,

apologies for the bug. `Access violation` means it's trying to read memory from an array index that is out-of-bounds.

- Is the stl file in the correct directory `FluidX3D/stl/fiel.stl`?
- Does it work when you choose a different device, like the GPU instead of CPU?
- If you comment out the line `//lbm.voxelize_stl(...);`, does the bug still appear?
- Is it one of the sample setups, and if not, could you share the setup script and stl file (link)?

Kind regards,
Moritz

**Comment by xx005fs** [comment]
The stl file is in the correct directory and runs perfectly fine on my GPU. I wanted to run on my CPU due to the limited VRAM I have compared to my system ram. The bug seems to still be there even after commenting out the voxelize line, and I'm just using the aerodynamics of a cow sample setup with the STL downloaded from thingiverse.

**Comment by xx005fs** [comment]
I am using the intel opencl library that is the newest version on GitHub. I also tried the version on Intel's download center, which has the same issue. I tried POCL as well but didn't have much success on Windows.

**Comment by xx005fs** [comment]
Sorry I accidentally closed the issue. But in anycase, I'm using the newest intel oneAPI opencl on the github link provided.

**Comment by ProjectPhysX** [comment]
Hi @xx005fs,

I found the root cause and have [fixed](https://github.com/ProjectPhysX/FluidX3D/commit/d55be40ffcc62321b111dfa79c707638d9ccd8bd) this bug!
Thanks again for reporting and thanks for the patience!

Kind regards,
Moritz
