### ISSUE TITLE
Resolution of voxels

### ISSUE THREAD

**Issue by Hydrag1** [ProjectPhysX/FluidX3D#149]
Hi there,

I tried to experiment a bit with the software and it's really incredible but I'm stuck with something pretty simple.
How do I reduce the size of the voxels that are generated from the STL files?
In the trailer videos it's always high-res but the settings in the setup file are rather blocky.

I tried to increase the resolution by making the 

 uint3 lbm_N = resolution(float3(1.0f, 1.0f, 1.0f), 5000u)

Larger, so 1.0 --> 100.0 or even 1000.0 but it still tells me in the render that my resolution has the same values. I'm not sure if I'm supposed to change the units maybe, so 1.0f is like 1 cm instead of a meter of if there is a function to control the amount of voxels produced. 

Thank you for the help  and best regards

**Comment by ProjectPhysX** [comment]
Hi @Hydrag1,

the `uint3 lbm_N = resolution(float3(1.0f, 1.0f, 1.0f), 5000u);` functions's arguments mean the following:
- The `float3(1.0f, 1.0f, 1.0f)` is the x/y/z aspect ratio of the cuboid simulation box, here a 1x1x1 which means it's a cube. The absolute values don't matter, `float3(300.0f, 300.0f, 300.0f)` would be the same cube. And `float3(100.0f, 1.0f, 1.0f)` for example would mean the simulation box is a long quadratic channel along x-direction.
- The `5000u` is the amount of VRAM you want the simulation to occupy, in MegaByte. Make this number larger and the resolution will increase and voxels will be smaller. Of course you can only allocate as much VRAM as physically present on the GPU, and typically a few hundred MB less, like maximum `23500u` MegaByte on a 24GB GPU (there is some overhead for operating system, and FluidX3D also needs a few MB for the frame buffer when rendering).
- The return value of the function (`uint3 lbm_N`) is the actuall grid resolution, with x/y/z components. This is later passed into the [LBM constructor](https://github.com/ProjectPhysX/FluidX3D/blob/master/DOCUMENTATION.md#the-lbm-class).

That said, to get the max resolution out of te available VRAM, you can [enable FP16S compression](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/defines.hpp#L13). This reduces the amount of memory each voxel needs from 93 Byte to 55 Byte, so `5000u` MB will hold 95M voxels instead of 65M.

If you need even higher resolution than your GPU's limited VRAM can hold, there is also options:
- You can [run FluidX3D on the CPU](https://github.com/ProjectPhysX/FluidX3D/issues/148#issuecomment-1959949707), with the typically larger RAM capacity. This will be much slower though.
- In case you have a multi-GPU setup, or some old decommisioned GPUs around, FluidX3D can pool their VRAM together. For this, tell the [LBM constructor](https://github.com/ProjectPhysX/FluidX3D/blob/master/DOCUMENTATION.md#the-lbm-class) to use multiple domains, like `LBM lbm(lbm_N, 2u, 2u, 1u, ...)` to run on 2x2x1=4 GPUs. It's possible to ["SLI" GPUs from different vendors](https://youtu.be/PscbxGVs52o), as long as VRAM capacity and bandwidth are similar.
- [Google Colab](https://colab.research.google.com/) offers free access to a Tesla T4 GPU with 15GB VRAM.
- As a last resort, consider upgrading to a GPU with more VRAM capacity.

Kind regards,
Moritz
