### ISSUE TITLE
What exactly is the definition of scale

### ISSUE THREAD

**Issue by wjsjtu123** [ProjectPhysX/FluidX3D#159]
![image](https://github.com/ProjectPhysX/FluidX3D/assets/160718220/a3de19eb-47d2-40a5-a278-b64bd79deaa5)
![image](https://github.com/ProjectPhysX/FluidX3D/assets/160718220/92753b9c-4da9-41ab-8ddc-ce5f2057dc65)
![image](https://github.com/ProjectPhysX/FluidX3D/assets/160718220/bde70897-ab3e-4ff8-9a85-8dae3ebdebff)
I would like to know exactly how this **scale** variable should be defined and what exactly it means in the code

**Comment by ProjectPhysX** [comment]
Hi @wjsjtu123,

- `lbm_length` is 40% of the longest side of the simulation box (let's say 300 LBM cells long).
- `fuselage->get_bounding_box_size().x` is the length of the fuselage mesh, as it is loaded from `.stl` coordinates (could be 10 for example); the `.x` component here is the length because the mesh is rotated such that its length is along the x-axis
- `scale` is the ratio of the two
- applying `scale`  to the `fuselage` mesh first divides its length by itself (`fuselage->get_bounding_box_size().x`) so that it now is 1 LBM cell long, and then multiplies by `lbm_length` to make it 300 LBM cells long
- this allows to make the mesh always the same size within the LBM simulation box, regardless how large or small it was in `.stl` coordinates

Kind regards,
Moritz
