### ISSUE TITLE
Interactive Graphics mode not fully rendering image in multi-GPU setups.

### ISSUE THREAD

**Issue by SLGY** [ProjectPhysX/FluidX3D#219]
Whenever I use `#define INTERACTIVE_GRAPHICS` mode on a 3 x Tesla K80 system (and Ryzen 5700G processor) the visuals suffer a significant fault. In the saved sequential images (and also visible on screen) some of the GPU volumes do not appear, whilst others do. It's not every frame, but >50% of the saved images have some of the volumes missing. I have included a video of the issue which is saved at 1 FPS to show it clearly. Some frames show all 6 volumes whilst others only show 1 or 2.

It's like some of the students are late for the class photo, so the photo is taken without them that year.

https://github.com/user-attachments/assets/5ccc9c11-e0d3-41e2-8b17-916eea6552b1

It happens in all setups, regardless of the GPU memory allocation or the resolution of the saved image (tested down to 720p and up to 4K).

I do not get the same problem for the same setup in `#define GRAPHICS` mode. This usually wouldn't be an issue as I can just use `INTERACTIVE_GRAPHICS` to setup the simulation and then just run it in `GRAPHICS` mode, but for this particular video I need a 'slice' of information (i.e. toggling through volume slices using `key_T`) which isn't available in GRAPHICS mode, as I haven't been able to work out how to directly set `slice_mode` or the `slice_x`, `slice_y` or `slice_z` in my _setup.cpp_.

Is there something I can do to help fault-find here? I can also post the detailed system specs here too if that helps diagnose the issue.

**Comment by ProjectPhysX** [comment]
Hi @SLGY,

for now don't mix `INTERACTIVE_GRAPHICS` and `lbm.graphics.write_frame()`.

You can use `slice_mode` in regular `GRAPHICS` and do all settings from within `main_setup()`:
```c
lbm.graphics.visualization_modes |= VIS_FIELD;
lbm.graphics.field_mode = 0; // field_mode = { 0 (u), 1 (rho), 2 (T) }
lbm.graphics.slice_mode = 1; // slice_mode = { 0 (no slice), 1 (x), 2 (y), 3 (z), 4 (xz), 5 (xyz), 6 (yz), 7 (xy) }
lbm.graphics.slice_x = (int)lbm.get_Nx()/2; // slice_{xyz} = position of slices
```

Kind regards,
Moritz

**Comment by ProjectPhysX** [comment]
Hi @SLGY,

this bug is now [fixed](https://github.com/ProjectPhysX/FluidX3D/commit/034076048930449b411907a1c87b0a06bf5bed85#diff-b0ec52269255a923607e08208f1208efa9a69b0941a18fed4ed144851647ec79R1212) in update [v2.19](https://github.com/ProjectPhysX/FluidX3D/releases/tag/v2.19). Thanks for reporting!

What happened there was that while `lbm.camera.write_frame()` was half-way assembling the new image from GPU domains, the interactive graphics render thread would sometimes swap the pointer to the bitmap, and then rendering continued on the bitmap for the next frame. I solved it with mutex locks.

Kind regards,
Moritz

PS: You're gonna love the [Catmull-Rom splines feature](https://github.com/ProjectPhysX/FluidX3D/blob/master/DOCUMENTATION.md#video-rendering) for smooth camera movement!
