### ISSUE TITLE
Python wrapper for blender integration

### ISSUE THREAD

**Issue by Jcwscience** [ProjectPhysX/FluidX3D#225]
I’ve been using blender for over a decade and as soon as I saw this project the possibilities have been swirling around my head. I am fairly adept at python but unfortunately not cpp. I’m willing to make an attempt at it though, the idea of realtime fluid simulation in blender is too cool to pass up. If I were to aim at handling as much as possible with wrapper scripts, where would you recommend I start? Or rather what would a conceptual pipeline look like? At first glance I was thinking of exporting the mesh and settings from blender, running the simulation in FluidX, and dumping the data out through a shared memory buffer back to blender.

I don’t expect to accomplish too much as it’s sort of a hobby project, but since I’ll probably take a stab at it anyway I figure it can’t hurt to ask for advice.

Thanks!

**Comment by ProjectPhysX** [comment]
Hi @Jcwscience,

I don't think Blender integration is feasible and/or useful. FluidX3D is a standalone application, with in-situ rendering in OpenCL. Blender cannot handle such large volumetric datasets in real time. The only way would be to forward user controls, let FluidX3D simulate and render, and forward the viewport back; but what is the purpose of Blender then?
I've decided against a UI fur building the setups, as it's too much limitation in what you can do. Instead, I allow users to write the `main_setup()` function directly in C++, with all of the language's features. Building a Python wrapper for that is possible, but honestly just a huge pain for reduction in functionality. Also a Python wrapper would still require thorough knowledge of the C++ backend, so there is no way around C++.
My recommendation is to learn C++. The basics are enough, you don't need any of the fancy stuff like inharitance or templaces. Really just basics, loops, conditions, functions, a bit of std library. C++ is a very valuable skill. There is some really good YouTube playlists for learning C++, for example [this one from The Cherno](https://www.youtube.com/watch?v=18c3MTX0PK0&list=PL6QsGpwbUoXEtxpPdjQ0GQQgwoYX2zwim).

Kind regards,
Moritz

**Comment by gitcnd** [comment]
My "inline_things" branch here https://github.com/gitcnd/FluidX3D/tree/inline_things is a heavily modified version of the source which makes every feature of the code available as a single command line program.  I did this in preparation for converting the code into a native python module (which I plan to complete later this year).
I've "paused" for a moment while I consider the task of adding the ability for this code to also work on Mac graphics - it looks like it's almost trivially possible to manage that, but my Mac's old and sick and the idea of supporting both intel and arm silicon on that platform erases the word "trivial" from the problem...

I added the ability to run it in a Window (instead of fullscreen) on Windows, and it already has hooks to send the output elsewhere (image files or to make a movie) so that might be most of the way towards what you need?

Here's an example of running the program (launching it from WSL on windows) and writing the frames out to a folder for making a movie

start "cmd.exe '/c mode con: lines=80 & powershell -Command \"& { [console]::BufferWidth = 160; [console]::BufferHeight = 9999 }\" & bin\FluidX3D.exe -f ../../Dustless_Fanblade.stl -r 15400 --SUBGRID --roty 90 --rotz 90 --try -0.2 -c 0.2 -u 13 --aoa -4.4 --fps 60 --SRT --UPDATE_FIELDS --GRAPHICS --EQUILIBRIUM_BOUNDARIES --FP16S --D3Q27 --export png_fine/ --slomo 10 --scale 1 --width 0.025 --length 0.2 --height 0.05 & pause'"  # 131 x 1048 x 262 = 35969456

I'm planning on making it auto-detect everything shortly, so all the scale and width and sizes etc are fully automatic... (requiring you to use stl files in either mm or inches so it knows how to get that right).

It's a few commits behind at present - if you need any new features/fixes since my last sync - let me know and I'll merge and update it all.

**Comment by Meerkov** [comment]
> I did this in preparation for converting the code into a native python module (which I plan to complete later this year).

I don't expect the project owner to support Python, but converting is pretty easy. I modified it to be callable from `cupy` in python with some minor edits to `kernel.cpp` and `defines.cpp` to change from OpenCL to something cupy supports natively. Commandline is a possibility too, though I assume then you have to deal with interprocess communication.
