### ISSUE TITLE
Support for external compositing with high fidelity 3D models of vehicle and environment for enhanced visualizations

### ISSUE THREAD

**Issue by lk251** [ProjectPhysX/FluidX3D#232]
Dr. Lehmann,
This idea comes from the arts and not the sciences or engineering, so I don't expect it to be a priority.

I wonder if the simulation data (like velocity and vorticity fields) could be exported each frame for compositing with external renders in software like Blender, so that flow visualization may be integrated with photorealistic models and environments.

I would be interested in contributing to this effort.
Thank you for your attention and your magnificent piece of software.
Javier

**Comment by ProjectPhysX** [comment]
Hi @lk251,

volumetric data export for external analysis/rendering is already possible, in binary `.vtk` format, see [here](https://github.com/ProjectPhysX/FluidX3D/blob/master/DOCUMENTATION.md#data-export).
The problem is that file size is gigantic, and a couple thousand frames will need many TB of hard disk space. Exporting so much data will also blow up the runtime by ~100x, as hard drive write speed becomes the new bottleneck. For large simulations, in-situ rendering is the only viable option.

Kind regards,
Moritz
