### ISSUE TITLE
Need additional boundary conditions for velocity and temperature

### ISSUE THREAD

**Issue by rodionstepanov** [ProjectPhysX/FluidX3D#233]
Hi! How to set the boundary conditions:
1) free slip for velocity. Is it equivalent to `TYPE_F`?
2) fixed heat flux for temperature. 
By the way, it is not quite clear what boundary conditions for temperature are obtained on the side walls in example setup `thermal convection`? I can guess isothermal or periodic condition. Please clarify

**Comment by ProjectPhysX** [comment]
Hi @rodionstepanov,

- free-slip boundaries are not implemented - I could not yet find a solution for cells in concave corners, and without this special case it doesn't work correctly for arbitrary geometries
  - `TYPE_F` is for the [free surface extension](https://github.com/ProjectPhysX/FluidX3D/blob/master/DOCUMENTATION.md#surface-extension)
  - instead of free-slip, you can use [moving bounce-back boundaries](https://github.com/ProjectPhysX/FluidX3D/blob/master/DOCUMENTATION.md#initial-and-boundary-conditions) (enable the [`MOVING_BOUNDARIES`](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/defines.hpp) extension, set boundaray cells to `TYPE_S` and set their velocity during initial conditions)
- [temperature boundaries](https://github.com/ProjectPhysX/FluidX3D/blob/master/DOCUMENTATION.md#temperature-extension) can be set with `TYPE_T` flag - they should be the fluid cells adjacent to solid boundaries, not the `TYPE_S` cells themselves

Kind regards,
Moritz

**Comment by rodionstepanov** [comment]
Thank you @ProjectPhysX  for response but I asked too much at once to be clear.
Could you please clarify what would be boundary conditions for temperature on the side walls in the example setup `thermal convection`? I see there it set non-periodic boundary with tag `TYPE_S`. What does it lead for temperature?

**Comment by ProjectPhysX** [comment]
@rodionstepanov without any flags set, the simulation box has periodic boundary conditions in x/y/z. In the `thermal convection` setup, all sides of the simulation box are set `TYPE_S`, so that boundaries are now all non-periodic and it's an enclosed box. Then, next to the `TYPE_S` walls in y-direction, the adjacent layers left and right are set as thermal boundaries with `TYPE_T`; this flag fixes the temperature value (`lbm.T`) in those cells to whatever was value was set during initial conditions; it puts no other constraints on flow velocity in those cells.
With one hot and one cold side wall, and volume force downwards, thermal convection flow emerges.

**Comment by rodionstepanov** [comment]
@ProjectPhysX sorry for my stupidity but what is boundary condition for temperature in x,z-directions (I call boundary  in these directions as side walls in respects to temperature jump in y-direction)?

**Comment by ProjectPhysX** [comment]
@rodionstepanov in the `thermal convection` setup there is walls all around, so the flow is non-periodic in all directions. Where there is no `TYPE_T` boundaries set (x,z), the temperature is unconstrained to be whatever the fluid there has as temperature.

**Comment by rodionstepanov** [comment]
@ProjectPhysX it sounds a bit unphysical. Temperature is advected with a fluid motion and diffuses itself. Right? So there should be boundary  conditions for temperature to provide a isothermal condition for example.
