### ISSUE TITLE
Massive Slowdown on Zoom

### ISSUE THREAD

**Issue by Meerkov** [ProjectPhysX/FluidX3D#234]
![image](https://github.com/user-attachments/assets/e6be15cd-d925-48e1-ad07-a7ff98d1f994)

Zooming into the center of a simulation with the fields showing will slow the simulation to a crawl, or even nearly freeze it. I'm not exactly sure why.

**Comment by ProjectPhysX** [comment]
Hi @Meerkov,

this is due to triangle rasterization, when a single triangle covers large parts of the screen. The one GPU thread drawing that large triangle then blocks all other threads in the workgroup drawing smaller triangles, and blows up overall runtime of the rendering kernel. I've already set thresholds for the maximum triangle screen area ([here](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/kernel.cpp#L275) and [here](https://github.com/ProjectPhysX/FluidX3D/blob/master/src/kernel.cpp#L302)) as `200²` pixels, and you can decrease that value if needed. It will skip rendering larger triangles then.

Kind regards,
Moritz
