### ISSUE TITLE
Graphics - Frozen Picture or Black Background 

### ISSUE THREAD

**Issue by Jmedelli** [ProjectPhysX/FluidX3D#92]
Hi Dr. Moritz, thank you for sharing your work. When I run the sample programs, it goes through compiling, opens the window, but it stays black, or it would sometimes show a picture which comes out frozen. The right lower area with Fps however runs, but it seems something is off with my computer not being able to show the picture. Do you know what could it be?

Not sure if it helps, but this is what I got for my benchmark test. 

|-----------------------------------------------------------------------------|
|----------------.------------------------------------------------------------|
| Device ID    0 | GeForce 210                                                |
|----------------'------------------------------------------------------------|
|----------------.------------------------------------------------------------|
| Device ID      | 0                                                          |
| Device Name    | GeForce 210                                                |
| Device Vendor  | NVIDIA Corporation                                         |
| Device Driver  | 342.01                                                     |
| OpenCL Version | OpenCL C 1.1                                               |
| Compute Units  | 2 at 1238 MHz (256 cores, 0.634 TFLOPs/s)                  |
| Memory, Cache  | 1024 MB, 0 KB global / 16 KB local                         |
| Buffer Limits  | 256 MB global, 64 KB constant                              |
|----------------'------------------------------------------------------------|
| Info: OpenCL C code successfully compiled.                                  |
| Info: Allocating memory. This may take a few seconds.                       |
|-----------------.-----------------------------------------------------------|
| Grid Resolution |                                256 x 256 x 256 = 16777216 |
| Grid Domains    |                                             1 x 1 x 1 = 1 |
| LBM Type        |                                    D3Q19 SRT (FP32/FP16S) |
| Memory Usage    |                                 CPU 272 MB, GPU 1x 880 MB |
| Max Alloc Size  |                                                    608 MB |
| Time Steps      |                                                        10 |
| Kin. Viscosity  |                                                1.00000000 |
| Relaxation Time |                                                3.50000000 |
| Reynolds Number |                                                  Re < 148 |
|---------.-------'-----.-----------.-------------------.---------------------|
| MLUPs   | Bandwidth   | Steps/s   | Current Step      | Time Remaining      |
|  397821 |  30632 GB/s |     23712 |         7789  90% |                  0s |
|---------'-------------'-----------'-------------------'---------------------|
| Info: Peak MLUPs/s = 498874                                                 |

Best regards,
Jordi

**Comment by ProjectPhysX** [comment]
Hi @Jmedelli,

together with the graphics window a second console window will open in the background. Click to free the mouse, then Alt+Tab to the console window. This will show you error messages if something does not work. I strongly assume that your GT 210 1GB GPU has not enough VRAM for most of the ssample setups as-is. But you can reduce resolution in the sample setups. If there is a line
```c
const uint3 lbm_N = resolution(float3(..., ..., ...), 2000u);
```
then the `2000u` is how much VRAM the setup will use in MB. Reduce this to maybe 700MB; your operating system might occupy ~300MB already. You see this in the standard Benchmark already: Even though it only needs 880MB VRAM and your GPU has 1GB, it fails to run the kernel as the OS has some overhead, and reports an unphysically quick runtime, because the kernel is not executed at all.

So try with lower resolution.

Kind regards,
Moritz

**Comment by Jmedelli** [comment]
Thank you for your help!
